export const VEHICLE_BRANDS = {
  auto: [
    'Audi',
    'BMW',
    'Citroën',
    'Dacia',
    'Ford',
    'Honda',
    'Hyundai',
    'Kia',
    'Mazda',
    'Mercedes-Benz',
    'Opel',
    'Porsche',
    'Renault',
    'Skoda',
    'Smart',
    'Toyota',
    'Volkswagen',
    'Volvo',
    'Andere',
  ],
  motorrad: [
    'BMW',
    'Ducati',
    'Honda',
    'Kawasaki',
    'KTM',
    'Suzuki',
    'Yamaha',
    'Andere',
  ],
  baumaschine: [
    'Avant',
    'Bobcat',
    'Caterpillar',
    'Claas',
    'Doosan',
    'HYSTER',
    'JCB',
    'Komatsu',
    'Kramer',
    'Kubota',
    'LI-ION',
    'Liebherr',
    'Linde',
    'Manitou',
    'Merlo',
    'Palfinger',
    'Schäffer',
    'Still',
    'Takeuchi',
    'Volvo',
    'Wacker',
    'Weidemann',
    'Yanmar',
    'Andere',
  ],
} as const;

export const VEHICLE_TYPE_LABELS = {
  auto: 'Fahrzeug',
  motorrad: 'Motorrad',
  baumaschine: 'Baumaschine',
} as const;

export type VehicleType = keyof typeof VEHICLE_BRANDS;
