import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { useCart } from '@/contexts/CartContext';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { ArrowLeft, Minus, Plus, Trash2, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

const Warenkorb: React.FC = () => {
  const { user, profile, isApproved } = useAuth();
  const { items, updateQuantity, removeFromCart, clearCart, totalPrice } = useCart();
  const navigate = useNavigate();
  const { toast } = useToast();
  
  const [isOrdering, setIsOrdering] = useState(false);
  const [showCheckout, setShowCheckout] = useState(false);
  const [shippingData, setShippingData] = useState({
    address: profile?.address || '',
    city: profile?.city || '',
    postalCode: profile?.postal_code || '',
    notes: '',
  });

  const handleOrder = async () => {
    if (!user || !isApproved) {
      toast({
        title: 'Nicht berechtigt',
        description: 'Ihr Konto muss freigeschaltet sein, um Anfragen zu senden.',
        variant: 'destructive',
      });
      return;
    }

    if (items.length === 0) {
      toast({
        title: 'Keine Produkte ausgewählt',
        description: 'Fügen Sie Produkte hinzu, bevor Sie eine Anfrage senden.',
        variant: 'destructive',
      });
      return;
    }

    setIsOrdering(true);

    try {
      // Create the order/request
      const { data: orderData, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          total_amount: totalPrice,
          shipping_address: shippingData.address,
          shipping_city: shippingData.city,
          shipping_postal_code: shippingData.postalCode,
          notes: shippingData.notes || null,
          order_number: '', // Will be generated by trigger
        } as any)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map((item) => ({
        order_id: orderData.id,
        product_id: item.product.id,
        product_name: item.product.name,
        quantity: item.quantity,
        unit_price: item.product.price,
        total_price: item.product.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Clear cart and show success
      clearCart();
      toast({
        title: 'Anfrage gesendet!',
        description: `Ihre Angebotsanfrage ${orderData.order_number} wurde erfolgreich übermittelt. Wir melden uns schnellstmöglich bei Ihnen.`,
      });
      navigate('/portal/anfragen');
    } catch (error) {
      console.error('Error creating request:', error);
      toast({
        title: 'Fehler',
        description: 'Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.',
        variant: 'destructive',
      });
    } finally {
      setIsOrdering(false);
    }
  };

  if (items.length === 0 && !showCheckout) {
    return (
      <div className="min-h-screen bg-background">
        <header className="border-b bg-card">
          <div className="container mx-auto px-4 py-4">
            <Button variant="ghost" asChild>
              <Link to="/portal">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Zurück zum Portal
              </Link>
            </Button>
          </div>
        </header>
        <main className="container mx-auto px-4 py-16">
          <Card className="max-w-md mx-auto text-center">
            <CardContent className="pt-8">
              <FileText className="h-16 w-16 mx-auto text-muted-foreground mb-4" />
              <h3 className="text-lg font-medium mb-2">Keine Produkte ausgewählt</h3>
              <p className="text-muted-foreground mb-4">
                Wählen Sie Produkte aus, für die Sie ein Angebot anfordern möchten.
              </p>
              <Button asChild>
                <Link to="/portal">Zum Produktkatalog</Link>
              </Button>
            </CardContent>
          </Card>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card">
        <div className="container mx-auto px-4 py-4">
          <Button variant="ghost" asChild>
            <Link to="/portal">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Zurück zum Portal
            </Link>
          </Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <h1 className="text-2xl font-bold mb-8">Angebotsanfrage</h1>

        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-4">
            {items.map((item) => (
              <Card key={item.product.id}>
                <CardContent className="p-4">
                  <div className="flex items-center gap-4">
                    {item.product.image_url ? (
                      <img
                        src={item.product.image_url}
                        alt={item.product.name}
                        className="w-20 h-20 object-cover rounded-md"
                      />
                    ) : (
                      <div className="w-20 h-20 bg-muted rounded-md flex items-center justify-center">
                        <FileText className="h-8 w-8 text-muted-foreground" />
                      </div>
                    )}
                    <div className="flex-1">
                      <h3 className="font-medium">{item.product.name}</h3>
                      <p className="text-muted-foreground">
                        ca. {item.product.price.toLocaleString('de-DE', {
                          style: 'currency',
                          currency: 'EUR',
                        })}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button
                        variant="outline"
                        size="icon"
                        onClick={() => updateQuantity(item.product.id, item.quantity - 1)}
                      >
                        <Minus className="h-4 w-4" />
                      </Button>
                      <span className="w-8 text-center">{item.quantity}</span>
                      <Button
                        variant="outline"
                        size="icon"
                        onClick={() => updateQuantity(item.product.id, item.quantity + 1)}
                      >
                        <Plus className="h-4 w-4" />
                      </Button>
                    </div>
                    <p className="font-bold w-24 text-right">
                      ca. {(item.product.price * item.quantity).toLocaleString('de-DE', {
                        style: 'currency',
                        currency: 'EUR',
                      })}
                    </p>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => removeFromCart(item.product.id)}
                    >
                      <Trash2 className="h-4 w-4 text-destructive" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div>
            <Card>
              <CardHeader>
                <CardTitle>Ihre Anfrage</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex justify-between">
                  <span>Geschätzter Wert</span>
                  <span>
                    ca. {totalPrice.toLocaleString('de-DE', {
                      style: 'currency',
                      currency: 'EUR',
                    })}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground">
                  Die endgültigen Preise erhalten Sie in Ihrem individuellen Angebot.
                </p>

                {showCheckout ? (
                  <div className="space-y-4 pt-4 border-t">
                    <div className="space-y-2">
                      <Label htmlFor="address">Lieferadresse</Label>
                      <Input
                        id="address"
                        value={shippingData.address}
                        onChange={(e) => setShippingData({ ...shippingData, address: e.target.value })}
                        placeholder="Straße und Hausnummer"
                      />
                    </div>
                    <div className="grid grid-cols-2 gap-2">
                      <div className="space-y-2">
                        <Label htmlFor="postalCode">PLZ</Label>
                        <Input
                          id="postalCode"
                          value={shippingData.postalCode}
                          onChange={(e) => setShippingData({ ...shippingData, postalCode: e.target.value })}
                          placeholder="12345"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="city">Stadt</Label>
                        <Input
                          id="city"
                          value={shippingData.city}
                          onChange={(e) => setShippingData({ ...shippingData, city: e.target.value })}
                          placeholder="Stadt"
                        />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="notes">Nachricht / Anforderungen</Label>
                      <Textarea
                        id="notes"
                        value={shippingData.notes}
                        onChange={(e) => setShippingData({ ...shippingData, notes: e.target.value })}
                        placeholder="Besondere Wünsche oder Anforderungen..."
                        rows={4}
                      />
                    </div>
                  </div>
                ) : null}
              </CardContent>
              <CardFooter className="flex-col gap-2">
                {showCheckout ? (
                  <>
                    <Button
                      className="w-full"
                      onClick={handleOrder}
                      disabled={isOrdering || !shippingData.address || !shippingData.city || !shippingData.postalCode}
                    >
                      {isOrdering ? 'Wird gesendet...' : 'Angebotsanfrage senden'}
                    </Button>
                    <Button
                      variant="outline"
                      className="w-full"
                      onClick={() => setShowCheckout(false)}
                    >
                      Zurück
                    </Button>
                  </>
                ) : (
                  <Button className="w-full" onClick={() => setShowCheckout(true)}>
                    Weiter zur Anfrage
                  </Button>
                )}
              </CardFooter>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Warenkorb;
